export const studentLifeData = {
  discounts: {
    categories: ['Toate', 'Transport', 'Divertisment', 'Tech & Apps', 'Muzică & Media', 'Restaurant', 'Cultură', 'VPN & Securitate', 'Productivitate'],
    offers: [
      // ── Transport ──────────────────────────────────────────────────────────────
      {
        id: 1,
        brand: 'CTP Iași',
        initials: 'CTP',
        color: '#2563eb',
        category: 'Transport',
        discount: 90,
        city: 'Iași',
        popular: true,
        verified: true,
        description: 'Abonament lunar transport public cu 90% reducere (Legea nr. 199/2023). Aplici la ghișeele CTP cu carnetul vizat.',
      },
      // ── Divertisment ──────────────────────────────────────────────────────────
      {
        id: 2,
        brand: 'Cinema City Iași',
        initials: 'CC',
        color: '#1e293b',
        category: 'Divertisment',
        discount: 50,
        city: 'Iași',
        popular: true,
        verified: true,
        description: 'Bilete la preț redus cu carnetul de student vizat sau ISIC. Valabil la Cinema City Iulius Mall Iași.',
      },
      {
        id: 3,
        brand: 'ISIC Card',
        initials: 'IS',
        color: '#0369a1',
        category: 'Divertisment',
        discount: 42,
        city: 'all',
        popular: true,
        verified: true,
        description: 'Card internațional de student (50 RON / 16 luni) — acces la 42.000+ reduceri în 130 de țări: H&M, IKEA, parteneri locali Iași și multe altele.',
      },
      // ── Muzică & Media ────────────────────────────────────────────────────────
      {
        id: 4,
        brand: 'Spotify Student',
        initials: 'SP',
        color: '#16a34a',
        category: 'Muzică & Media',
        discount: 46,
        city: 'all',
        popular: true,
        verified: true,
        description: 'Spotify Premium la 14 RON/lună (față de 26 RON). Valabil până la 4 ani în timpul studiilor. Verificare prin SheerID cu email instituțional.',
      },
      {
        id: 5,
        brand: 'Apple Music Student',
        initials: 'AM',
        color: '#374151',
        category: 'Muzică & Media',
        discount: 50,
        city: 'all',
        popular: true,
        verified: true,
        description: 'Apple Music la 11,99 RON/lună + Apple TV+ gratuit inclus. Valabil până la 48 de luni. Verificare prin SheerID.',
      },
      {
        id: 6,
        brand: 'YouTube Premium Student',
        initials: 'YT',
        color: '#dc2626',
        category: 'Muzică & Media',
        discount: 50,
        city: 'all',
        popular: false,
        verified: true,
        description: 'YouTube Premium fără reclame la ~50% reducere față de planul standard. Include YouTube Music. Verificare prin SheerID.',
      },
      // ── Tech & Apps ───────────────────────────────────────────────────────────
      {
        id: 7,
        brand: 'Adobe Creative Cloud',
        initials: 'AD',
        color: '#dc2626',
        category: 'Tech & Apps',
        discount: 65,
        city: 'all',
        popular: true,
        verified: true,
        description: 'Adobe Creative Cloud complet (Photoshop, Illustrator, Premiere Pro etc.) la prețuri instituționale — până la 65% reducere față de planul individual.',
      },
      {
        id: 8,
        brand: 'GitHub Student Pack',
        initials: 'GH',
        color: '#171717',
        category: 'Tech & Apps',
        discount: 100,
        city: 'all',
        popular: true,
        verified: true,
        description: 'GitHub Student Developer Pack — gratuit! Include GitHub Pro, JetBrains IDEs, domenii Namecheap, credite cloud și 100+ unelte dev. Aplici pe education.github.com.',
      },
      {
        id: 9,
        brand: 'Microsoft 365 Education',
        initials: 'MS',
        color: '#0078d4',
        category: 'Tech & Apps',
        discount: 100,
        city: 'all',
        popular: true,
        verified: true,
        description: 'Microsoft 365 A1 complet gratuit pentru studenți cu email instituțional (@student.uaic.ro). Word, Excel, PowerPoint, Teams, 1 TB OneDrive.',
      },
      {
        id: 10,
        brand: 'Canva Pro',
        initials: 'CV',
        color: '#7c3aed',
        category: 'Tech & Apps',
        discount: 100,
        city: 'all',
        popular: false,
        verified: true,
        description: 'Canva Pro complet gratuit prin programul Canva Education. Aplici cu emailul instituțional pe canva.com/education.',
      },
      {
        id: 11,
        brand: 'Notion Student',
        initials: 'NO',
        color: '#171717',
        category: 'Productivitate',
        discount: 100,
        city: 'all',
        popular: false,
        verified: true,
        description: 'Notion Personal Pro plan gratuit pentru studenți. Note, baze de date, proiecte de echipă — nelimitat. Aplici pe notion.com/students.',
      },
      // ── VPN & Securitate ──────────────────────────────────────────────────────
      {
        id: 12,
        brand: 'NordVPN Student',
        initials: 'NV',
        color: '#4f46e5',
        category: 'VPN & Securitate',
        discount: 76,
        city: 'all',
        popular: false,
        verified: true,
        description: 'NordVPN cu până la 76% reducere prin StudentBeans. Verifici statusul de student și primești cod de reducere.',
      },
      // ── Cultură ───────────────────────────────────────────────────────────────
      {
        id: 13,
        brand: 'Teatrul Național Iași',
        initials: 'TN',
        color: '#7c2d12',
        category: 'Cultură',
        discount: 75,
        city: 'Iași',
        popular: false,
        verified: true,
        description: 'Bilete la spectacole cu reducere de până la 75% pentru studenți (conform legislației în vigoare privind instituțiile publice de cultură). Prezinți carnetul vizat.',
      },
      {
        id: 14,
        brand: 'Complexul Muzeal Moldova',
        initials: 'MM',
        color: '#047857',
        category: 'Cultură',
        discount: 75,
        city: 'Iași',
        popular: false,
        verified: true,
        description: 'Intrare redusă la toate muzele din Complexul Muzeal Moldova Iași (Palatul Culturii, Muzeul Unirii etc.) cu carnet de student vizat.',
      },
      // ── Restaurant / Cantina ──────────────────────────────────────────────────
      {
        id: 15,
        brand: 'Cantinele UAIC',
        initials: 'CU',
        color: '#ea580c',
        category: 'Restaurant',
        discount: 50,
        city: 'Iași',
        popular: true,
        verified: true,
        description: 'Mese subvenționate la cantinele universității (Copou, Tătărași). Meniu zilnic la prețuri reduse — verifică oferta pe uaic.ro.',
      },
    ],
  },

  career: {
    CS: [
      {
        id: 101,
        company: 'Amazon Development Center Iași',
        initials: 'AZ',
        color: '#f59e0b',
        role: 'Software Development Engineer Intern',
        baseMatch: 92,
        remote: false,
        paid: true,
        tags: ['Java', 'AWS', 'Distributed Systems'],
        type: 'Internship',
        minYear: 2,
        cities: ['Iași'],
      },
      {
        id: 102,
        company: 'Endava Iași',
        initials: 'EN',
        color: '#7c3aed',
        role: 'Software Engineer Intern',
        baseMatch: 88,
        remote: false,
        paid: true,
        tags: ['Java', 'React', 'Agile', 'REST APIs'],
        type: 'Internship',
        minYear: 1,
        cities: ['Iași'],
      },
      {
        id: 103,
        company: 'Bitdefender',
        initials: 'BD',
        color: '#dc2626',
        role: 'Junior ML Engineer Intern',
        baseMatch: 84,
        remote: false,
        paid: true,
        tags: ['Python', 'Machine Learning', 'Cybersecurity'],
        type: 'Internship',
        minYear: 3,
        cities: ['Iași'],
      },
      {
        id: 104,
        company: 'Cegeka România',
        initials: 'CG',
        color: '#0369a1',
        role: 'Junior Software Developer',
        baseMatch: 80,
        remote: false,
        paid: true,
        tags: ['.NET', 'Azure', 'ERP', 'Cloud'],
        type: 'Internship',
        minYear: 2,
        cities: ['Iași'],
      },
      {
        id: 105,
        company: 'evozon',
        initials: 'EV',
        color: '#059669',
        role: 'AI Internship (Data Science)',
        baseMatch: 82,
        remote: true,
        paid: true,
        tags: ['Python', 'Data Science', 'AI', 'ML'],
        type: 'Internship',
        minYear: 2,
        cities: ['Iași', 'all'],
      },
      {
        id: 106,
        company: 'ASII / LSAC Iași',
        initials: 'AS',
        color: '#6366f1',
        role: 'Voluntar Organizare Eveniment Tech',
        baseMatch: 65,
        remote: false,
        paid: false,
        tags: ['Networking', 'Organizare', 'Events'],
        type: 'Voluntariat',
        minYear: 1,
        cities: ['Iași'],
      },
    ],
    MEDICINE: [
      {
        id: 201,
        company: 'Spitalul Universitar „Sf. Spiridon" Iași',
        initials: 'SS',
        color: '#dc2626',
        role: 'Student Clinician (Stagiu Clinică)',
        baseMatch: 93,
        remote: false,
        paid: false,
        tags: ['Clinică', 'Semiologie', 'Medicină Internă'],
        type: 'Internship',
        minYear: 3,
        cities: ['Iași'],
      },
      {
        id: 202,
        company: 'Antibiotice SA Iași',
        initials: 'AB',
        color: '#0369a1',
        role: 'Stagiar Producție Farmaceutică',
        baseMatch: 80,
        remote: false,
        paid: true,
        tags: ['Farmacie', 'GMP', 'Producție', 'Chimie'],
        type: 'Internship',
        minYear: 3,
        cities: ['Iași'],
      },
      {
        id: 203,
        company: 'UMF „Gr. T. Popa" Iași',
        initials: 'UF',
        color: '#7c3aed',
        role: 'Asistent Cercetare (Voluntar)',
        baseMatch: 72,
        remote: false,
        paid: false,
        tags: ['Cercetare', 'Statistică', 'Publicații'],
        type: 'Cercetare',
        minYear: 3,
        cities: ['Iași'],
      },
      {
        id: 204,
        company: 'Synevo Iași',
        initials: 'SY',
        color: '#2563eb',
        role: 'Stagiar Analize Medicale',
        baseMatch: 78,
        remote: false,
        paid: true,
        tags: ['Biochimie', 'Laborator', 'LIMS'],
        type: 'Internship',
        minYear: 2,
        cities: ['Iași'],
      },
    ],
    ECONOMICS: [
      {
        id: 301,
        company: 'Deloitte România',
        initials: 'DL',
        color: '#65a30d',
        role: 'Audit Intern',
        baseMatch: 88,
        remote: false,
        paid: true,
        tags: ['Audit Financiar', 'Excel', 'IFRS'],
        type: 'Internship',
        minYear: 2,
        cities: ['Iași'],
      },
      {
        id: 302,
        company: 'BCR Iași',
        initials: 'BC',
        color: '#dc2626',
        role: 'Analist Financiar Intern',
        baseMatch: 82,
        remote: false,
        paid: true,
        tags: ['Banking', 'Financial Modelling', 'Excel'],
        type: 'Internship',
        minYear: 1,
        cities: ['Iași'],
      },
      {
        id: 303,
        company: 'eMAG',
        initials: 'EM',
        color: '#f26522',
        role: 'Marketing Intern',
        baseMatch: 77,
        remote: true,
        paid: true,
        tags: ['Digital Marketing', 'SEO', 'Analytics'],
        type: 'Internship',
        minYear: 1,
        cities: ['all'],
      },
    ],
    LAW: [
      {
        id: 401,
        company: 'Baroul Iași',
        initials: 'BI',
        color: '#1e3a8a',
        role: 'Asistent Juridic Junior',
        baseMatch: 86,
        remote: false,
        paid: false,
        tags: ['Drept Civil', 'Procedură', 'Redactare acte'],
        type: 'Internship',
        minYear: 3,
        cities: ['Iași'],
      },
      {
        id: 402,
        company: 'ELSA Iași',
        initials: 'EL',
        color: '#374151',
        role: 'Voluntar Organizare Moot Court',
        baseMatch: 74,
        remote: false,
        paid: false,
        tags: ['Drept European', 'Moot Court', 'Networking'],
        type: 'Voluntariat',
        minYear: 1,
        cities: ['Iași'],
      },
    ],
    ARCHITECTURE: [
      {
        id: 501,
        company: 'Biro Arhitectura Iași',
        initials: 'BA',
        color: '#7c3aed',
        role: 'Design Assistant',
        baseMatch: 84,
        remote: false,
        paid: true,
        tags: ['AutoCAD', 'Revit', '3ds Max'],
        type: 'Internship',
        minYear: 2,
        cities: ['Iași'],
      },
    ],
  },

  community: {
    activities: ['Fotbal', 'Baschet', 'Alergare', 'Gaming', 'Grup de studiu', 'Cafea', 'Drumeție', 'Cinema', 'Startup', 'Schimb lingvistic', 'Voluntariat', 'Hackathon'],
    groups: [
      {
        id: 1,
        name: 'ASII — Studenți Informatică UAIC',
        type: 'Tech',
        description: 'Asociația Studenților Informaticieni Ieșeni (est. 1990) — hackathoane, workshop-uri, InfoIT Fair, networking cu companii IT din Iași.',
        members: 120,
        interests: ['coding', 'tech', 'startup'],
        open: true,
      },
      {
        id: 2,
        name: 'ESN Iași — Erasmus Students',
        type: 'Social',
        description: 'Erasmus Student Network Iași — 60+ voluntari, petreceri internaționale, City Tour, excursii în România. Perfecte pentru a-ți extinde cercul de prieteni.',
        members: 60,
        interests: ['social', 'travel', 'limbi_straine'],
        open: true,
      },
      {
        id: 3,
        name: 'LSAC Iași — Automatică & IT',
        type: 'Tech',
        description: 'Liga Studenților din Automatică și Calculatoare. Organizează InfoIT Fair (cel mai mare târg de joburi IT studențesc din Moldova) și cursuri tehnice.',
        members: 85,
        interests: ['coding', 'tech', 'startup'],
        open: true,
      },
      {
        id: 4,
        name: 'ELSA Iași — Drept European',
        type: 'Studiu',
        description: 'Asociația Europeană a Studenților în Drept — moot court-uri, seminarii juridice, trainee-ship-uri. Câștigătoarea premiului "Best Local Group" ELSA România.',
        members: 45,
        interests: ['study', 'drept', 'networking'],
        open: true,
      },
      {
        id: 5,
        name: 'V7 Startup Studio Iași',
        type: 'Tech',
        description: 'Hub de startup-uri în Palas (UBC3). Coworking, mentori, investitori, evenimente antreprenoriale. Ideal dacă vrei să-ți lansezi o idee de business.',
        members: 90,
        interests: ['startup', 'tech', 'coding'],
        open: false,
      },
      {
        id: 6,
        name: 'Fotbal Studenți Copou',
        type: 'Sport',
        description: 'Meciuri 5vs5 relaxate pe terenurile din zona Copou/Tătărași în fiecare sâmbătă dimineața. Toate nivelele de pregătire binevenite.',
        members: 18,
        interests: ['football', 'sport'],
        open: true,
      },
      {
        id: 7,
        name: 'Club Cinema Vineri — Iași',
        type: 'Social',
        description: 'Film nou la Cinema City Iulius Mall în fiecare vineri, cu discount de grup. Discuții despre film după proiecție la cafenelele din mall.',
        members: 12,
        interests: ['movies', 'social'],
        open: true,
      },
      {
        id: 8,
        name: 'Pregătire Algoritmi & Concursuri',
        type: 'Studiu',
        description: 'Grup de pregătire pentru InfoEducație, ACM ICPC și interviuri tehnice. Rezolvăm probleme de algoritmică, DP și structuri de date în sesiuni săptămânale.',
        members: 14,
        interests: ['coding', 'study'],
        open: true,
      },
    ],
  },
}

export const facultyCareerKeys = {
  CS: 'CS',
  IT: 'CS',
  INFO: 'CS',
  MATH_CS: 'CS',
  MED: 'MEDICINE',
  MEDICINE: 'MEDICINE',
  ECONOMICS: 'ECONOMICS',
  ECON: 'ECONOMICS',
  LAW: 'LAW',
  ARCHITECTURE: 'ARCHITECTURE',
  ARCH: 'ARCHITECTURE',
}

export const eventsData = [
  { id: 'ev1', title: 'Hackathon FiiPractic 2026', date: '2026-05-20', time: '09:00', location: 'UAIC Corp A, Iași', category: 'Tech', going: 234, color: '#6366f1', description: '48 de ore de cod, idei și pizza. Cel mai mare hackathon studențesc din Moldova.' },
  { id: 'ev2', title: 'Concert Studenți', date: '2026-05-25', time: '20:00', location: 'Palatul Culturii, Iași', category: 'Muzică', going: 512, color: '#ec4899', description: 'Seară de muzică live cu trupe studențești. Intrare gratuită cu carnet.' },
  { id: 'ev3', title: 'Bursa Locurilor de Muncă UAIC', date: '2026-05-28', time: '10:00', location: 'Sala Polivalentă, Iași', category: 'Carieră', going: 389, color: '#10b981', description: '30+ companii tech prezente. Aduce CV-ul și fii pregătit pentru interviu pe loc.' },
  { id: 'ev4', title: 'Noaptea Cercetătorilor', date: '2026-06-02', time: '18:00', location: 'UAIC, toate corpurile', category: 'Știință', going: 178, color: '#f59e0b', description: 'Experimente, demonstrații și prezentări de la cercetătorii UAIC. Intrare liberă.' },
  { id: 'ev5', title: 'Student Startup Pitch', date: '2026-06-05', time: '14:00', location: 'Hub Iași', category: 'Antreprenoriat', going: 145, color: '#8b5cf6', description: 'Prezintă-ți ideea de business în față investitorilor. Premii în valoare de 10.000€.' },
  { id: 'ev6', title: 'Film Club — Indie Night', date: '2026-06-08', time: '19:00', location: 'Cinema arta, Iași', category: 'Cultură', going: 89, color: '#06b6d4', description: 'Proiecție de scurtmetraje studențești urmată de dezbatere cu regizorii.' },
  { id: 'ev7', title: 'Olimpiada Informaticii', date: '2026-06-10', time: '09:00', location: 'FII UAIC', category: 'Tech', going: 203, color: '#6366f1', description: 'Concurs de algoritmică open pentru studenți. Primele 3 locuri primesc internship la Endava.' },
  { id: 'ev8', title: 'Gala Absolvenților FII', date: '2026-06-15', time: '18:00', location: 'Hotel Moldova, Iași', category: 'Social', going: 456, color: '#f97316', description: 'Ceremonia de premiere a absolvenților promoției 2026. Dresscode: smart casual.' },
]

export const booksData = [
  { id: 'bk1', title: 'Algoritmi și Structuri de Date', author: 'Knuth', subject: 'Informatică', yearNeeded: 2, condition: 'Bună', price: 0, type: 'donez', contact: 'Rareș B.', faculty: 'FII' },
  { id: 'bk2', title: 'Calcul Diferențial și Integral', author: 'Boboc', subject: 'Matematică', yearNeeded: 1, condition: 'Foarte bună', price: 30, type: 'vând', contact: 'Maria C.', faculty: 'FII' },
  { id: 'bk3', title: 'Baze de Date — Teorie și Practică', author: 'Fotache', subject: 'Baze de Date', yearNeeded: 2, condition: 'Uzată', price: 15, type: 'vând', contact: 'Andrei P.', faculty: 'FII' },
  { id: 'bk4', title: 'Fizică pentru Ingineri Vol. 1', author: 'Halliday', subject: 'Fizică', yearNeeded: 1, condition: 'Bună', price: 40, type: 'vând', contact: 'Elena M.', faculty: 'FII' },
  { id: 'bk5', title: 'Programare Orientată Obiect în Java', author: 'Horstmann', subject: 'POO', yearNeeded: 2, condition: 'Bună', price: 0, type: 'donez', contact: 'Claudiu T.', faculty: 'FII' },
  { id: 'bk6', title: 'Rețele de Calculatoare', author: 'Tanenbaum', subject: 'Rețele', yearNeeded: 3, condition: 'Foarte bună', price: 60, type: 'vând', contact: 'Denis I.', faculty: 'FII' },
  { id: 'bk7', title: 'Sisteme de Operare', author: 'Silberschatz', subject: 'SO', yearNeeded: 3, condition: 'Bună', price: 35, type: 'vând', contact: 'Ioana R.', faculty: 'FII' },
  { id: 'bk8', title: 'Inteligență Artificială — O abordare modernă', author: 'Russell & Norvig', subject: 'AI', yearNeeded: 4, condition: 'Nouă', price: 80, type: 'vând', contact: 'Mihai S.', faculty: 'FII' },
]

export const carpoolData = [
  { id: 'cp1', from: 'Iași', to: 'București', date: '2026-05-23', time: '07:30', seats: 2, driver: 'Alex M.', pricePerPerson: 60, contact: '@alexm', verified: true },
  { id: 'cp2', from: 'Iași', to: 'Cluj-Napoca', date: '2026-05-24', time: '08:00', seats: 3, driver: 'Ioana R.', pricePerPerson: 80, contact: '@ioanar', verified: true },
  { id: 'cp3', from: 'București', to: 'Iași', date: '2026-05-25', time: '16:00', seats: 1, driver: 'Dan V.', pricePerPerson: 60, contact: '@danv', verified: false },
  { id: 'cp4', from: 'Iași', to: 'Suceava', date: '2026-05-23', time: '14:00', seats: 2, driver: 'Maria T.', pricePerPerson: 30, contact: '@mariat', verified: true },
  { id: 'cp5', from: 'Iași', to: 'Bacău', date: '2026-05-24', time: '15:00', seats: 3, driver: 'Cristi P.', pricePerPerson: 25, contact: '@cristip', verified: false },
  { id: 'cp6', from: 'Iași', to: 'Timișoara', date: '2026-05-31', time: '06:00', seats: 2, driver: 'Radu M.', pricePerPerson: 120, contact: '@radum', verified: true },
]

export const roommateData = [
  { id: 'rm1', name: 'Maria C.', faculty: 'FII', year: 2, budget: '800-1000 RON/lună', zone: 'Copou', smoking: false, pets: false, schedule: 'Matinal', bio: 'Caut colegă serioasă pentru apartament 2 camere în Copou. Sunt ordonată și liniștită.', contact: '@mariac' },
  { id: 'rm2', name: 'Andrei P.', faculty: 'FII', year: 3, budget: '600-800 RON/lună', zone: 'Podu Roș', smoking: false, pets: true, schedule: 'Flexibil', bio: 'Caut 1-2 colegi pentru apartament 3 camere. Am pisică prietenoasă. Gătim împreună?', contact: '@andreip' },
  { id: 'rm3', name: 'Elena M.', faculty: 'Medicină', year: 1, budget: '700-900 RON/lună', zone: 'Tătărași', smoking: false, pets: false, schedule: 'Variabil', bio: 'Studentă la Medicină, program intens. Caut coleg/colegă tolerant/ă cu orele ciudate.', contact: '@elenam' },
  { id: 'rm4', name: 'Bogdan T.', faculty: 'FII', year: 4, budget: '500-700 RON/lună', zone: 'Manta Roșie', smoking: false, pets: false, schedule: 'Nocturn', bio: 'Developer, lucrez mult de acasă. Caut apartament liniștit, preferabil cu internet bun.', contact: '@bogdant' },
  { id: 'rm5', name: 'Ioana R.', faculty: 'Drept', year: 2, budget: '900-1200 RON/lună', zone: 'Copou', smoking: false, pets: false, schedule: 'Matinal', bio: 'Caut colegă în Copou, aproape de facultate. Sunt ordonată, gătesc bine.', contact: '@ioanar' },
]

export const wellnessData = {
  contacts: [
    { id: 'wc1', name: 'Consiliere Psihologică UAIC', phone: '0232-201-000', email: 'consiliere@uaic.ro', available: 'L-V, 9:00-17:00', type: 'Psiholog', free: true },
    { id: 'wc2', name: 'Linia de criză TESA', phone: '0800-070-800', available: '24/7', type: 'Urgențe', free: true },
    { id: 'wc3', name: 'Ambulatoriu Studențesc', phone: '0232-214-100', available: 'L-V, 8:00-20:00', type: 'Medicină', free: true },
    { id: 'wc4', name: 'Sala de Sport UAIC', phone: '0232-201-234', available: 'L-D, 7:00-22:00', type: 'Sport', free: false },
  ],
  tips: [
    { id: 'wt1', icon: '🧠', title: 'Tehnica Pomodoro', body: '25 minute focus, 5 minute pauză. Crește productivitatea cu până la 40%.' },
    { id: 'wt2', icon: '😴', title: 'Somnul contează', body: '7-8 ore pe noapte îmbunătățesc memoria și concentrarea. Nu sacrifica somnul pentru studiu.' },
    { id: 'wt3', icon: '🏃', title: 'Mișcare zilnică', body: '30 minute de mers pe jos reduc anxietatea cu 50%. Ieși din cameră.' },
    { id: 'wt4', icon: '🍎', title: 'Mânâncă regulat', body: 'Sare peste mese = concentrare slabă. Cantina studențească e ieftină și accesibilă.' },
    { id: 'wt5', icon: '📵', title: 'Detox digital', body: 'O oră fără telefon înainte de culcare îmbunătățește calitatea somnului semnificativ.' },
    { id: 'wt6', icon: '🤝', title: 'Vorbește cu cineva', body: 'Nu ești singur. Consilierea psihologică UAIC e gratuită și confidențială.' },
  ],
  pomodoroConfig: { work: 25, shortBreak: 5, longBreak: 15, sessionsUntilLong: 4 },
}
